service: mirko-notifier-service
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  profile: sls_framework
  region: eu-west-1
  runtime: nodejs8.10
  environment:
    appkey: d99b6pFK8f
    secretkey: z7nF82zdPy
    dynamo_table: mirko_notifier
    sns_topic: EmailNotificationTopic
    sns_topic_arn: arn:aws:sns:eu-west-1:505701054639:EmailNotificationTopic
    region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:*:*:table/${self:provider.environment.dynamo_table}
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: arn:aws:sns:*:*:${self:provider.environment.sns_topic}

functions:
  notify:
    handler: handler.run
    memorySize: 512
    timeout: 5
    events:
        # 10am UTC, daily
      - schedule: cron(0 9,12,15,18,20 * * ? *)
resources:
  Resources:
    TagDefinitionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.dynamo_table}
        AttributeDefinitions:
          - AttributeName: tag
            AttributeType: S
        KeySchema:
          - AttributeName: tag
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    EmailNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.environment.sns_topic}
